# Generated by Django 5.1.1 on 2024-10-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="food",
            new_name="foodItems",
        ),
    ]
