# Generated by Django 5.1.1 on 2024-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_rename_food_fooditems"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("complted", models.BooleanField(default=False)),
            ],
        ),
    ]
